order:
  - item: overview
  - item: browser
    hide: true
  - item: media
  - item: docs
  - item: photos
  - item: grocy
  - item: security

  - item: admin
    bottom: true
  - item: hacs
    bottom: true
  - item: map
    hide: true
  - item: logbook
    bottom: true
  - item: history
    bottom: true
