repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler
  - name: jetstack
    url: https://charts.jetstack.io
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts
  - name: rook
    url: https://charts.rook.io/release
  - name: nextcloud
    url: https://nextcloud.github.io/helm
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: tekton
    url: https://eddycharly.github.io/tekton-helm
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: nfd
    #url: git+https://github.com/kubernetes-sigs/node-feature-discovery/deployment/helm
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  - name: nicholaswilde
    url: https://nicholaswilde.github.io/helm-charts/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts/
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: kiali
    url: https://kiali.org/helm-charts

environments:
  default:
    values:
    - hostname: bryton.io
      email: email@bryton.io
      timezone: America/New_York
      username: hall
      address:
        domain: lan
        pool:
          - 192.168.1.2-192.168.1.9
        ip:
          router:  192.168.1.1
          dns:     192.168.1.2
          ingress: 192.168.1.3
          accessPoints:
            - 192.168.1.2
          controlPlanes:
            - 192.168.1.10

releases:
{{- range $_, $file := exec "bash" (list "-c" "echo -n releases/*") | splitList " " }}
  {{ $name := trimSuffix ".yaml.gotmpl" (base $file) }}
  {{- if eq $name "media" -}}
    {{ range $chart, $version := (dict
      "jellyfin"    "~9"
      "lidarr"      "~13"
      "ombi"        "~11"
      "prowlarr"    "~4"
      "qbittorrent" "~13"
      "radarr"      "~15"
      "readarr"     "~6"
      "sonarr"      "~12"
    )}}
  - name: {{ $chart }}
    chart: k8s-at-home/{{ $chart }}
    version: {{ $version }}
    namespace: default
    values:
      - {{ $file }}
    {{ end }}
  {{ else }}
  - name: {{ $name }}
{{ tpl (readFile $file) $ | indent 4 }}
  {{- end }}
{{- end }}

  - name: misc
    chart: incubator/raw
    namespace: default
    values:
    - templates:
        # install manifests under ./manifests
        {{- range $_, $path :=  ( exec "sh" (list "-c" "echo -n manifests/*.yaml*") | splitList " " ) }}
        - |
{{ tpl (readFile $path) $ | indent 14}}
        {{- end }}
