packages:
  common: !include .common.yaml

wifi:
  ssid: hall
  password: !secret wifi
  domain: .lan
  # use_address: unassigned-power

  ap:
    ssid: $name Hotspot
    password: !secret wifi

captive_portal:

sensor:
  - platform: wifi_signal
    name: $name WiFi Strength
    update_interval: 60s
