variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOMAIN: bryton.io

stages:
  - deploy

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
    - public
  environment:
    name: prod
    url: https://$DOMAIN
  only:
    - master

