- id: attic_temperature
  alias: maintain attic temperature
  trigger:
    platform: state
    entity_id:
      - binary_sensor.rental_water_heater_flood
      - binary_sensor.sump_pump_flood
      - binary_sensor.water_heater_flood
      - binary_sensor.washing_machine_flood
    to: "on"
  action:
    - service: notify.mobile_app_sm_n950u1
      data_template:
        message: "{{ trigger.entity_id }} leak detected"
        data:
# 68F <= temp <= 10-20F + outside temp; max 130F
# few degrees colder is fine
#
# 10-50% in winter
# <= 70%
#
# 1sqft of vent / 300sqft floor space
