- id: door_garage
  alias: automatic garage door
  trigger:
    platform: state
    entity_id: binary_sensor.car
    to: # otherwise, will trigger for attribute changes
      - "off"
      - "on"
  condition: # calling open/close would toggle w/o verifying state
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity: trigger.to_state
              state: "on"
            - condition: state
              entity: cover.garage_door
              state: closed
        - condition: and
          conditions:
            - condition: state
              entity: trigger.to_state
              state: "off"
            - condition: state
              entity: cover.garage_door
              state: open
  action:
    service: cover.toggle
    target:
      entity_id: cover.garage_door
