- id: rain_alert
  alias: Notify of rain chance in the next 24h
  trigger:
    platform: template
    value_template: state_attr('weather.home', 'forecast')[0].condition) == "rainy"
  action:
    service: notify.matrix
    data:
      message: >
        {{ trigger.json.message }}
