- id: torrent_notification
  alias: Completed Torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.matrix
    data:
      message: >
        download complete: {{ trigger.event.data.name }}
