- id: vacuum
  alias: Vacuum (on even days)
  trigger:
    platform: time
    at: "10:00"
  condition:
    condition: template
    value_template: >
      {{ now().day % 2 == 0 }}
  action:
    service: vacuum.start
    data:
      entity_id: vacuum.roomba
